### ISSUE TITLE
theme issues

### ISSUE THREAD

**Issue by nisainan** [ztalab/ZAPortal#10]
I changed theme from dark to light,but where I refresh the page , it rolled back

**Comment by rovast** [comment]
Issue reviewed, the choice of theme should be cached in the browser. Maybe the localstorage is required.

- [ ] Save the choice with local storage
- [ ] Read the value if needed

**Comment by rovast** [comment]
For the better track of the issue, the topic has been moved to #12 . Thank you for your feedback.

- #12
