### ISSUE TITLE
I hope to add the functions of viewing cert PEM and deleting data

### ISSUE THREAD

**Issue by Murphy-hub** [ztalab/ZAPortal#21]
## Overview

1. The client, server and relay lack the function of viewing cert PEM
2. Client, server, relay and resource management. I hope to add deletion function

## TODO

- [x] Add button to view and copy cert pem of clients, servers and relay.
- [ ] #22

## Reference

- None

**Comment by rovast** [comment]
I have split this issue into two issues, and now focus in the first issue: add cert pem.

The deletion function can be seen at #22 

---

And now I'm working on the pem function.

**Comment by rovast** [comment]
This issue is for the view of cert pem, and now `v0.0.3` is supported.

The deletion function will be tracked by #22.
